### ISSUE TITLE
Copy button overlaps with code snippets

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#197] opened 2017-05-11 22:27 UTC
Copy button is very useful, but in many cases it overlaps with code snippets.

example: istioctl command here
https://istio.io/docs/tasks/basic-access-control.html#access-control-using-denials

**Comment by ayj** [comment] 2017-05-11 22:30
This tends to happen when the screen width is reduced, e.g. side-by-side browser and terminal. 

<img width="372" alt="screen shot 2017-05-11 at 3 28 41 pm" src="https://cloud.githubusercontent.com/assets/116378/25974551/93f8ee3e-365e-11e7-8e35-84e425779978.png">

**Comment by ldemailly** [comment] 2017-05-12 22:55
This is same/duplicate of #174 (is there a "merge" button btw?)

**Closed** 2017-05-12 22:56 UTC
