### ISSUE TITLE
Bookinfo doc with auto-injection misses instruction

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.github.io#1303] opened 2018-05-17 20:01 UTC
Automatic injection is not enabled by default, even when sidecar injector is deployed.

Bookinfo instuctions must tell the user to label the namespace so that injection works.

**Comment by andraxylia** [comment] 2018-05-17 20:04
@hklai please add kind/blocking release label or some other way to indicate priority of doc issues.

**Comment by frankbu** [comment] 2018-07-16 20:30
Duplicate of https://github.com/istio/istio/issues/6957

**Closed by frankbu** 2018-07-16 20:30 UTC
Labels: area/environments, kind/docs
